### ISSUE TITLE
Failed to download because of the file name

### ISSUE THREAD

**Issue by mehdi-S** [sim0n00ps/GoFile-DL#1]
Hey there
got an error while trying to download this file https://gofile.io/d/sjLFGO | BALDURS GATE 3 UPDATE AIO TO v4.1.1.3767641 [GOG Galaxy] Hotfix9.7z
![image](https://github.com/sim0n00ps/GoFile-DL/assets/7304874/805c7054-8f5d-4308-8f87-afc9b2b66c74)

I suspect from the error message that you don't handle the title of files correctly and so the [] brackets make your script think that's a color tag

**Comment by sim0n00ps** [comment]
I think I've fixed the issue by escaping the markup on the file/folder names https://github.com/sim0n00ps/GoFile-DL/releases/tag/GoFileDLV1.2

**Comment by sim0n00ps** [comment]
I've tested with your link and you might have to go full screen to see the progress as the filename is quite big

**Comment by mehdi-S** [comment]
beware that this time i got a warning from chrome about the download 
![image](https://github.com/sim0n00ps/GoFile-DL/assets/7304874/115be1bb-fe8b-43ae-872c-becf21ef4591)

**Comment by mehdi-S** [comment]
other wise it seems to work well, as you said, visually the window have to be expended but issues solved
